# --------------
# -- Settings --
# --------------

# If you are hosting in a sub-folder, for example: https://mlh.github.io/mlh-hackathon-boilerplate/,
# you must specify it as the baseurl
# If you hosting as a root, for example: htttps://[github username].github.io, then leave it blank
baseurl: ""

# uncomment the next line if you are hosting as a root and not sub-folder
# for example, when runnig locally at http://127.0.0.1:4000/
# baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "http://fronterahacks.com/"

# The ability to use custom themes.
style:
  theme: "original"

# Let people connect & engage with you through social media.
social:
  - name: "Twitter"
    handle: "fronteradevsrgv"
    img: "images/social/twitter-black.svg"
    url: "https://twitter.com/fronteradevsrgv"
  - name: "Facebok"
    handle: "fronteradevsutrgv"
    img: "images/social/facebook-black.svg"
    url: "https://www.facebook.com/profile.php?id=100088968430072&mibextid=LQQJ4d"
  - name: "YouTube"
    handle: "Frontera Devs UTRGV"
    img: "images/social/youtube-black.svg"
    url: "https://www.youtube.com/channel/UCXHBRJsa9orzXiwIPGvNGSw"
  - name: "Discord"
    handle: "Frontera Hacks"
    img: "images/social/discord-black.svg"
    url: "https://discord.com/invite/fbf3HhN"
  - name: "Instagram"
    handle: "fronteradevs"
    img: "images/social/instagram-black.svg"
    url: "https://instagram.com/fronterahacks?igshid=MDM4ZDc5MmU="
# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title: "Frontera Hacks | 11-12 February 2023"
  description: "Frontera Hacks is the an inaugural 24-hour hackathon hosted by Frontera Devs."
  image: "_site/images/favicon.ico"

# Event information.
event:
  name: "Frontera Hacks"
  description: "Frontera Hacks is the an inaugural 24-hour hackathon hosted by Frontera Devs."
  tagline: "Accelerating innovation in the RGV"
  date: "11-12 February 2023"
  location: "Weslaco, TX, United States"

  trust_badge:
    year: "2023" # season year
    region: "na" # "na" or "eu"
    color: "white" # "white", "black", "gray", "red", "blue" or "yellow"

  # WE NEED TO TALK TO MLH ABOUT THIS.
  hero:
    links:
      - text: "Apply"
        my_mlh:
          client_id: "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          redirect_uri: "https://mlh.github.io/mlh-hackathon-boilerplate/success.html"
      - text: "Sponsor"
        href: "mailto:sponsorship@website.com"
    register:
        text: "Register"
        img: "images/register_banner.svg"
        href: "https://www.instagram.com/fronterahacks/?igshid=MDM4ZDc5MmU%3D"

  about:
    description: >
      Frontera Hacks is an inaugural 24-hour hackathon hosted by Frontera Devs that aims to foster a community of developers driven to innovate. At Frontera Hacks, we aim to provide an experience for developers of all skill levels to adopt skills taught outside of the classroom, collaborate with like-minded teams, and design projects with the potential to accelerate innovation in the Rio Grande Valley.

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "CONNECT."
        description: >
          Meet developers interested in shaping the future of innovation at Frontera Hacks
      - image: "images/image2.png"
        title: "GROW."
        description: >
          Advance your technical and interpersonal skills through our hands-on workshops 
      - image: "images/image3.png"
        title: "BUILD."
        description: >
          Develop solutions with the potential to aid and impact our community
  days:
    # Day 1 schedule
    - day: "February 11th, Saturday"
      gradient: gradient-h2-three
      slots:
        - time: "09:00AM"
          name: "Doors Open | Check-In"
        - time: "10:00AM"
          name: "Opening Ceremony"
        - time: "10:30AM"
          name: "Team Formation"
        - time: "11:30AM"
          name: "Hacking Begins"
        - time: "12:00AM"
          name: "De-stressing Area Opens"
        - time: "01:00PM"
          name: "Lunch"
        - time: "02:00PM"
          name: "Plotty Dash Workshop ft. Kristen Hallas"
        - time: "04:00PM"
          name: "Snyk Cybersecurity Challenge ft. Ellie"
        - time: "06:00PM"
          name: "Slideshow Karaoke"
        - time: "07:00PM"
          name: "Dinner"

    # Day 2 schedule
    - day: "February 12th, Sunday"
      gradient: gradient-h2-four
      slots:
        - time: "12:00AM"
          name: "Lo-fi and Chill"
        - time: "07:00AM"
          name: "Breakfast"
        - time: "08:00AM"
          name: "Headspace"
        - time: "12:00PM"
          name: "Submit Projects"
        - time: "01:00PM"
          name: "Lunch"
        - time: "01:30PM"
          name: "Women in Tech"
        - time: "02:00PM"
          name: "Judging"
        - time: "04:00PM"
          name: "Rewards Ceremony"

  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A hackathon is a sprint-like event where developers collaborate to build projects that solve challenges. At Frontera Hacks, hackers can look forward to educational workshops, learning from skilled mentors, and, of course, fun games and great swag.
    - question: "Who is this event for?"
      answer: >
        Students from all backgrounds are welcome at Frontera Hacks. No extensive knowledge of programming is necessary.
    - question: "Do I need a team to participate?"
      answer: >
        While teams are not required in order to participate, it’s a great way to meet new people and create something together. Teams may have up to 4 members, and you will have a chance to meet other hackers at our Team Formation events and in the Discord server!
    - question: "What is the cost to participate?"
      answer: >
        Nada, nothing, zilch. There is absolutely no cost for applying or participating in Frontera Hacks. We want to make this event as accessible as possible to all those interested so make sure you apply!

    - question: "What if I don’t know how to code?"
      answer: >
        No experience is needed — whether you're a coder, an artist, a designer, or a writer, you'll get a chance to work with various mentors, attend workshops, interact with companies, and learn alongside fellow participants.

    - question: "What if I need special accomodations?"
      answer: >
        Frontera Hacks prioritizes accessibility and accomodations that make our event welcoming for everyone. Please list any special accommodations in your admissions, or contact us with any other concerns.

  # sponsors list
  sponsors:
    - name: "HEB"
      image: "images/Sponsors/HEB/image 5.svg"
      url: "https://heb.com"
    - name: "CrowdStrike"
      image: "images/Sponsors/Crowdstrike/CrowdStrike_Logos/CS_Logos_2020_FullWhite_FullWhite.png"
      url: "http://www.crowdstrike.com/"
    - name: "GitHub"
      image: "images/Sponsors/GitHub/GitHub_Logo_White 1.svg"
      url: "https://github.com"
    - name: "MLH"
      image: "images/Sponsors/MLH/image 6.svg"
      url: "https://mlh.com"
    - name: "Rosenfeld Media"
      image: "images/Sponsors/Rosenfeld_Media/Asset 1 1.svg"
      url: "https://rosenfeldmedia.com/"
    - name: "Stand Out Stickers"
      image: "images/Sponsors/stand_out_stickers/StandOut_Stickers.svg"
      url: "http://hackp.ac/mlh-StandOutStickers-hackathons"
      #followup with taskade to see if they actually want sponsorship

  # This is the message you'll receive once you've registered.
  register:
    message: >
      Thank you for registering for Frontera Devs first hackathon! You'll receive more information closer to the hackathon!

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
